### ISSUE TITLE
AttributeError: 'CrossAttention' object has no attribute 'reshape_heads_to_batch_dim'

### ISSUE THREAD

**Issue by xiaqingsun** [adobe-research/custom-diffusion#23]
Has anyone encountered this problem “AttributeError: 'CrossAttention' object has no attribute 'reshape_heads_to_batch_dim' ”

**Comment by nupurkmr9** [comment]
Hi, 
pip install diffuser==0.11 should solve the problem for now.
I will update the code soon to support the new version of diffuser library. 

Thanks.

**Comment by xiaqingsun** [comment]
Thanks for your answer, it worked with diffuser==0.11.
The results I reproduced with the data in the paper are good

my input images:
![image](https://user-images.githubusercontent.com/106377665/217413213-c76cb46b-7ad4-453a-b78c-cf852ad6d65e.png)

my result:
![image](https://user-images.githubusercontent.com/106377665/217413295-a5946039-82d9-4d0a-9510-a1e0e046105d.png)
![image](https://user-images.githubusercontent.com/106377665/217414374-7c3d8f1c-3077-4d1e-be5c-ee674adae4ad.png)

But I change other pictures, the result is worse（the sunglasses is not  like my input sunglasses）

my input images:
![image](https://user-images.githubusercontent.com/106377665/217413487-6f730ec7-9809-4584-8b30-084500fccca2.png)

my result:
![image](https://user-images.githubusercontent.com/106377665/217413547-9cef70ea-c98d-4f0e-935e-0b05813cf91c.png)

My training parameters are as follows：（I use the pretrained_model: runwayml/stable-diffusion-v1-5）

!accelerate launch src/diffuser_training.py \
--pretrained_model_name_or_path=$MODEL_NAME \
--output_dir=$OUTPUT_DIR \
--concepts_list="/content/concepts_list.json" \
--with_prior_preservation --prior_loss_weight=1.0 \
--resolution=512 \
--train_batch_size=2 \
--learning_rate=1e-5 \
--lr_warmup_steps=0 \
--max_train_steps=500 \
--num_class_images=200 \
--scale_lr --hflip \
--modifier_token "\<whxm\>+\<bkmj\>"

My concept_list.json are as follows:
![image](https://user-images.githubusercontent.com/106377665/217416034-46fe2260-8b33-458c-af60-8e57b27767ec.png)

Is there something wrong with my training process causing this poor result？
Looking forward for your reply, thank you！

**Comment by wangzhaolei** [comment]
> Are you missing an s after diffuser，that  is  pip install diffusers==0.11，

**Comment by yannqi** [comment]
Another feasible way, you can change  'reshape_heads_to_batch_dim'  to 'head_to_batch_dim'
According to https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py
